# Generated by Django 3.2.7 on 2021-09-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uuid', models.CharField(default='44e3cb79f8e84721ade0831761b0e40c', max_length=32)),
                ('imageUrl', models.URLField(default='google.com')),
                ('event01', models.IntegerField(default=0)),
                ('event02', models.IntegerField(default=0)),
                ('event03', models.IntegerField(default=0)),
                ('event04', models.IntegerField(default=0)),
                ('event05', models.IntegerField(default=0)),
                ('event06', models.IntegerField(default=0)),
                ('event07', models.IntegerField(default=0)),
                ('event08', models.IntegerField(default=0)),
                ('event09', models.IntegerField(default=0)),
                ('event10', models.IntegerField(default=0)),
            ],
        ),
    ]
