# Generated by Django 3.2.7 on 2021-09-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_rename_players_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
        migrations.AddField(
            model_name='player',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField()),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leaderboard.player')),
            ],
        ),
    ]
