# Generated by Django 3.2.7 on 2021-09-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20210911_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imageUrl',
            field=models.URLField(default='https://www.mc-heads.net/avatar/MHF_Steve/32'),
        ),
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
