# Generated by Django 3.2.7 on 2021-09-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20210906_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='leaderboard.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='imageUrl',
            field=models.URLField(default='google.com'),
        ),
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.CharField(default='44e3cb79f8e84721ade0831761b0e40c', max_length=32),
        ),
    ]
